### ISSUE TITLE
Crashes when Trying to Edit Moves

### ISSUE THREAD

**Issue by TheKuro1970** [TheHeadmaster/Quartz#2]
**Version Number**
1.1.4

**Describe the bug**
As soon as I try to create a Move and go to edit it, the program crashes.

**To Reproduce**
1. Go to Moves
2. Insert Name
3. Program Crashes

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by TheHeadmaster** [comment]
Hi, could you by chance send me a zip of the project you're working on? I want to be able to repro the error you're getting.

**Comment by TheHeadmaster** [comment]
Nevermind, I have reproduced the issue. I will look into this further.

**Comment by TheHeadmaster** [comment]
fixed by [v1.1.5-alpha](/releases/tag/v1.1.5-alpha).
